name: Building GSI..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: hhg
  ROM_NAME: MIUI
  ZIP_NAME: MMX
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget

       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/qrovic/ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
              aria2c http://rom.download.nubia.com/Europe/NX659J/V411/NX659J-update.zip
              mv *.zip rom.zip
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/zip2img.sh ErfanGSIs/rom.zip
       
       - name: Zip Aonly and upload 
         run: |
              cd ErfanGSIs
              sudo mkdir lol
              cd ..
              sudo cp -r ErfanGSIs/cache/system.img ErfanGSIs/lol
              cd ErfanGSIs/lol
              sudo mkdir shet
              sudo mount -ro loop system.img shet/

       - name: ls shet
         run: |
              ls ErfanGSIs/lol/shet

       - name: ls system
         run: |
              ls ErfanGSIs/lol/shet/system

       - name: ls system/app
         run: |
              ls ErfanGSIs/lol/shet/system/app

       - name: ls system/priv-app
         run: |
              ls ErfanGSIs/lol/shet/system/priv-app

       - name: ls system/product/app
         run: |
              ls ErfanGSIs/lol/shet/system/product/app

       - name: ls system/product/app
         run: |
              ls ErfanGSIs/lol/shet/system/product/priv-app

       - name: ls system/product/app
         run: |
              ls ErfanGSIs/lol/shet/system/preset-app

       - name: Zip Aonly and upload 
         run: |  
              cd ErfanGSIs
              sudo ./make.sh lol/shet Pixel AB output
              
         
            
