name: Building GSI..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: hhg
  ROM_NAME: MIUI
  ZIP_NAME: MMX
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget

       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
              aria2c https://dl.google.com/developers/android/rvc/images/factory/walleye-rpb2.200611.012-factory-7e10760b.zip
              mv *.zip rom.zip
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/zip2img.sh ErfanGSIs/rom.zip
       
       - name: Zip Aonly and upload 
         run: |
              cd ErfanGSIs
              sudo mkdir lol
              cd ..
              sudo cp -r ErfanGSIs/cache/system.img ErfanGSIs/lol
              cd ErfanGSIs/lol
              sudo mkdir shet
              sudo chmod 0777 shet
              sudo mount -o ro system.img shet/
              ls shet/system/app
              ls shet/system/priv-app
              ls shet/system/product/app
              ls shet/system/product/priv-app
              ls shet/system/product
              ls shet/product
              
         
            
